<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
        targetNamespace="http://personservice" 
        xmlns="http://personservice" 
        xmlns:pers="http://person"
        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
        xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
      	 
        <xsd:schema targetNamespace="http://personservice" >
            
            <xsd:import namespace="http://person" 
                    schemaLocation="person.xsd" />

            <!-- Return value -->
            <xsd:element name="status" type="xsd:string" />
            
        </xsd:schema>

    </wsdl:types>

    <wsdl:message name="inMessage">
        <wsdl:part name="person" element="pers:person" />
    </wsdl:message>

    <wsdl:message name="outMessage">
        <wsdl:part name="status" element="status" />
    </wsdl:message>


    <wsdl:portType name="PersonService">

        <wsdl:operation name="add"  >
            <wsdl:input message="inMessage" />
            <wsdl:output message="outMessage" />
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="PersonServiceHTTPBinding" 
            type="PersonService">
        <wsdlsoap:binding style="document" 
            transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="add">
            <wsdlsoap:operation soapAction=""/>
             <wsdl:input>
                <wsdlsoap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <wsdlsoap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="PersonServicePorts">
        <wsdl:port binding="PersonServiceHTTPBinding"  name="PersonService">
            <wsdlsoap:address 
                location="http://localhost:9084/personService/PersonServicePorts"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
