INSERT INTO users VALUES (null, 'Kim', 'kim1@gmail.com', '1981-10-25', '1', 'REGISTERED_USER');
INSERT INTO users VALUES (null, 'Kim', 'kim2@gmail.com', '1982-10-31', '2', 'REGISTERED_USER,BOOKING_MANAGER');
INSERT INTO users VALUES (null, 'Ivan', 'ivan@gmail.com', '1983-12-01', '3', 'REGISTERED_USER');
INSERT INTO events VALUES (null, 'Minions', '2015-10-25', '15:00:00', 200, 'HIGH', 'Big');
INSERT INTO events VALUES (null, '007Spectr', '2015-10-30', '21:00:00', 100, 'MID', 'Mid');
INSERT INTO tickets VALUES (null, 1, null, 1, false);
INSERT INTO tickets VALUES (null, 1, 1, 2, true);
INSERT INTO tickets VALUES (null, 1, 1, 3, true);
INSERT INTO tickets VALUES (null, 1, 1, 4, true);
INSERT INTO tickets VALUES (null, 1, 1, 5, true);
INSERT INTO tickets VALUES (null, 1, 1, 6, true);
INSERT INTO tickets VALUES (null, 1, 1, 7, true);
INSERT INTO tickets VALUES (null, 1, 1, 8, true);
INSERT INTO tickets VALUES (null, 1, 1, 9, true);
INSERT INTO tickets VALUES (null, 1, 1, 10, true);
INSERT INTO tickets VALUES (null, 1, 1, 11, true);
INSERT INTO tickets VALUES (null, 2, null, 1, false);
INSERT INTO tickets VALUES (null, 2, null, 2, false);
INSERT INTO tickets VALUES (null, 2, null, 3, false);
INSERT INTO tickets VALUES (null, 2, null, 4, false);
INSERT INTO tickets VALUES (null, 2, 2, 5, true);
INSERT INTO tickets VALUES (null, 2, 2, 6, true);
INSERT INTO tickets VALUES (null, 2, 2, 7, true);
INSERT INTO tickets VALUES (null, 2, 2, 8, true);
INSERT INTO tickets VALUES (null, 2, 2, 9, true);
INSERT INTO tickets VALUES (null, 2, 2, 10, true);
INSERT INTO tickets VALUES (null, 2, 2, 11, true);
INSERT INTO tickets VALUES (null, 2, 2, 12, true);
INSERT INTO tickets VALUES (null, 2, 2, 13, true);
INSERT INTO tickets VALUES (null, 2, 2, 14, true);
INSERT INTO tickets VALUES (null, 2, 2, 15, true);
INSERT INTO tickets VALUES (null, 2, 2, 16, true);
INSERT INTO tickets VALUES (null, 2, 2, 17, true);
INSERT INTO tickets VALUES (null, 2, 2, 18, true);
INSERT INTO tickets VALUES (null, 2, 2, 19, true);
INSERT INTO tickets VALUES (null, 2, 2, 20, true);
INSERT INTO tickets VALUES (null, 2, 2, 21, true);
INSERT INTO tickets VALUES (null, 2, 2, 22, true);
INSERT INTO tickets VALUES (null, 2, 2, 23, true);
INSERT INTO tickets VALUES (null, 2, 2, 24, true);
INSERT INTO tickets VALUES (null, 2, 2, 25, true);
INSERT INTO tickets VALUES (null, 2, 2, 26, true);
INSERT INTO tickets VALUES (null, 2, 2, 27, true);
INSERT INTO tickets VALUES (null, null, null, 28, false);